# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfb04d8fd1a1cf7215f467688bcabdbcdd9573717f47d31929e761051606fd84ba097ca4278c8c42fcc4cb3b092aca8e34d7aba3a15c15a2b87dae8d3dc88f4d

test:
  secret_key_base: 1fd966d78389636e7dfebab0a435cada9f1668967fd42909bad84d55e9586d38c67edf33e2e456ccaf9fcec77a6b577a7e40ca2b1cf7bdd066d6d51092b51f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
